/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msg_sentinel.proto */

#ifndef PROTOBUF_C_msg_5fsentinel_2eproto__INCLUDED
#define PROTOBUF_C_msg_5fsentinel_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct MsgPayload MsgPayload;
typedef struct MsgMachineStatus MsgMachineStatus;


/* --- enums --- */


/* --- messages --- */

struct  MsgPayload
{
  ProtobufCMessage base;
  /*
   * 设备序列号 1000-9999，varint 2B
   */
  uint32_t sn;
  /*
   * event_type 0/1/2，varint 1B
   */
  uint32_t et;
  /*
   * Unix时间戳 ms，varint ~6B
   */
  uint64_t ts;
  /*
   * 对应 message 的序列化字节
   */
  ProtobufCBinaryData data;
};
#define MSG_PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&msg_payload__descriptor) \
, 0, 0, 0, {0,NULL} }


struct  MsgMachineStatus
{
  ProtobufCMessage base;
  /*
   * RMS X m/s²
   */
  float rx;
  float ry;
  float rz;
  /*
   * RMS均值
   */
  float rm;
  /*
   * 设备状态, 0 -> 关机,  1 -> 过度态, 2-> 稳定态
   */
  uint32_t st;
};
#define MSG_MACHINE_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&msg_machine_status__descriptor) \
, 0, 0, 0, 0, 0 }


/* MsgPayload methods */
void   msg_payload__init
                     (MsgPayload         *message);
size_t msg_payload__get_packed_size
                     (const MsgPayload   *message);
size_t msg_payload__pack
                     (const MsgPayload   *message,
                      uint8_t             *out);
size_t msg_payload__pack_to_buffer
                     (const MsgPayload   *message,
                      ProtobufCBuffer     *buffer);
MsgPayload *
       msg_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   msg_payload__free_unpacked
                     (MsgPayload *message,
                      ProtobufCAllocator *allocator);
/* MsgMachineStatus methods */
void   msg_machine_status__init
                     (MsgMachineStatus         *message);
size_t msg_machine_status__get_packed_size
                     (const MsgMachineStatus   *message);
size_t msg_machine_status__pack
                     (const MsgMachineStatus   *message,
                      uint8_t             *out);
size_t msg_machine_status__pack_to_buffer
                     (const MsgMachineStatus   *message,
                      ProtobufCBuffer     *buffer);
MsgMachineStatus *
       msg_machine_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   msg_machine_status__free_unpacked
                     (MsgMachineStatus *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MsgPayload_Closure)
                 (const MsgPayload *message,
                  void *closure_data);
typedef void (*MsgMachineStatus_Closure)
                 (const MsgMachineStatus *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor msg_payload__descriptor;
extern const ProtobufCMessageDescriptor msg_machine_status__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_msg_5fsentinel_2eproto__INCLUDED */
