/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msg_sentinel.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "msg_sentinel.pb-c.h"
void   msg_payload__init
                     (MsgPayload         *message)
{
  static const MsgPayload init_value = MSG_PAYLOAD__INIT;
  *message = init_value;
}
size_t msg_payload__get_packed_size
                     (const MsgPayload *message)
{
  assert(message->base.descriptor == &msg_payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg_payload__pack
                     (const MsgPayload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg_payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg_payload__pack_to_buffer
                     (const MsgPayload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg_payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MsgPayload *
       msg_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MsgPayload *)
     protobuf_c_message_unpack (&msg_payload__descriptor,
                                allocator, len, data);
}
void   msg_payload__free_unpacked
                     (MsgPayload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg_payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg_machine_status__init
                     (MsgMachineStatus         *message)
{
  static const MsgMachineStatus init_value = MSG_MACHINE_STATUS__INIT;
  *message = init_value;
}
size_t msg_machine_status__get_packed_size
                     (const MsgMachineStatus *message)
{
  assert(message->base.descriptor == &msg_machine_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg_machine_status__pack
                     (const MsgMachineStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg_machine_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg_machine_status__pack_to_buffer
                     (const MsgMachineStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg_machine_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MsgMachineStatus *
       msg_machine_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MsgMachineStatus *)
     protobuf_c_message_unpack (&msg_machine_status__descriptor,
                                allocator, len, data);
}
void   msg_machine_status__free_unpacked
                     (MsgMachineStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg_machine_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor msg_payload__field_descriptors[4] =
{
  {
    "sn",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MsgPayload, sn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "et",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MsgPayload, et),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ts",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MsgPayload, ts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MsgPayload, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg_payload__field_indices_by_name[] = {
  3,   /* field[3] = data */
  1,   /* field[1] = et */
  0,   /* field[0] = sn */
  2,   /* field[2] = ts */
};
static const ProtobufCIntRange msg_payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor msg_payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MsgPayload",
  "MsgPayload",
  "MsgPayload",
  "",
  sizeof(MsgPayload),
  4,
  msg_payload__field_descriptors,
  msg_payload__field_indices_by_name,
  1,  msg_payload__number_ranges,
  (ProtobufCMessageInit) msg_payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg_machine_status__field_descriptors[5] =
{
  {
    "rx",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MsgMachineStatus, rx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ry",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MsgMachineStatus, ry),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rz",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MsgMachineStatus, rz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rm",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MsgMachineStatus, rm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "st",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MsgMachineStatus, st),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg_machine_status__field_indices_by_name[] = {
  3,   /* field[3] = rm */
  0,   /* field[0] = rx */
  1,   /* field[1] = ry */
  2,   /* field[2] = rz */
  4,   /* field[4] = st */
};
static const ProtobufCIntRange msg_machine_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor msg_machine_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MsgMachineStatus",
  "MsgMachineStatus",
  "MsgMachineStatus",
  "",
  sizeof(MsgMachineStatus),
  5,
  msg_machine_status__field_descriptors,
  msg_machine_status__field_indices_by_name,
  1,  msg_machine_status__number_ranges,
  (ProtobufCMessageInit) msg_machine_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
