/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msg_machine_state.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "msg_machine_state.pb-c.h"
void   msg_machine_status__init
                     (MsgMachineStatus         *message)
{
  static const MsgMachineStatus init_value = MSG_MACHINE_STATUS__INIT;
  *message = init_value;
}
size_t msg_machine_status__get_packed_size
                     (const MsgMachineStatus *message)
{
  assert(message->base.descriptor == &msg_machine_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg_machine_status__pack
                     (const MsgMachineStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg_machine_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg_machine_status__pack_to_buffer
                     (const MsgMachineStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg_machine_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MsgMachineStatus *
       msg_machine_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MsgMachineStatus *)
     protobuf_c_message_unpack (&msg_machine_status__descriptor,
                                allocator, len, data);
}
void   msg_machine_status__free_unpacked
                     (MsgMachineStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg_machine_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor msg_machine_status__field_descriptors[7] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MsgMachineStatus, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "et",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MsgMachineStatus, et),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ts",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MsgMachineStatus, ts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MsgMachineStatus, rx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ry",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MsgMachineStatus, ry),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rz",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MsgMachineStatus, rz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rm",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MsgMachineStatus, rm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg_machine_status__field_indices_by_name[] = {
  1,   /* field[1] = et */
  0,   /* field[0] = id */
  6,   /* field[6] = rm */
  3,   /* field[3] = rx */
  4,   /* field[4] = ry */
  5,   /* field[5] = rz */
  2,   /* field[2] = ts */
};
static const ProtobufCIntRange msg_machine_status__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor msg_machine_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MsgMachineStatus",
  "MsgMachineStatus",
  "MsgMachineStatus",
  "",
  sizeof(MsgMachineStatus),
  7,
  msg_machine_status__field_descriptors,
  msg_machine_status__field_indices_by_name,
  2,  msg_machine_status__number_ranges,
  (ProtobufCMessageInit) msg_machine_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
